server:
  port: 8001
spring:
  application:
    name: ms-worker
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
mediastack:
  uri: ${MEDIASTACK_URI}
  api-key: ${MEDIASTACK_API_KEY}
  countries: US
  limit: 25