server:
  port: 8000
spring:
  application:
    name: ms-news
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}